version: "3.9"

services:
  identity-service:
    command: npm run dev
    volumes:
      - ../services/identity-service:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  account-service:
    command: npm run dev
    volumes:
      - ../services/account-service:/app
      - ../shared:/shared
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  ledger-service:
    command: npm run dev
    volumes:
      - ../services/ledger-service:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  api-gateway:
    command: npm run dev
    volumes:
      - ../services/api-gateway:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true