services:

  cockroachdb:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"

  identity-service:
    build:
      context: ..
      dockerfile: services/identity-service/Dockerfile

  account-service:
    build:
      context: ..
      dockerfile: services/account-service/Dockerfile

  api-gateway:
    build: ../services/api-gateway
    ports:
      - "3000:3000"